
import { 
  LayoutDashboard, 
  Store, 
  Receipt, 
  Settings, 
  Plus, 
  ArrowLeft, 
  CheckCircle2, 
  Clock, 
  XCircle, 
  Trash2, 
  Edit3,
  Search,
  Languages,
  Type,
  ChevronRight,
  AlertCircle,
  ArrowUpDown,
  Filter,
  Calendar,
  IndianRupee,
  X
} from 'lucide-react';
import React from 'react';
import { COLORS as CENTRAL_COLORS } from './colors';

export const API_URL = 'https://script.google.com/macros/s/AKfycbzda4Jz0iwOTd9V_wjfrNjtXREc8odo5SEtGpFokHkwvtkX3MCRsw4Co0X4iqOVjsfF/exec';

export const COLORS = CENTRAL_COLORS;

export const TRANSLATIONS = {
  en: {
    appName: 'BMA – Bill Manager',
    dashboard: 'Dashboard',
    shops: 'Shops',
    pendingBills: 'Pending Bills',
    amountToCollect: 'To Collect',
    totalShops: 'Total Shops',
    addShop: 'Add New Shop',
    addBill: 'Add New Bill',
    editShop: 'Edit Shop',
    deleteShop: 'Delete Shop',
    shopName: 'Shop Name',
    amount: 'Amount',
    status: 'Status',
    save: 'Save',
    cancel: 'Cancel',
    confirmDelete: 'Are you sure you want to delete?',
    noShops: 'No shops added yet',
    noPendingBills: 'No bills match these filters 🎉',
    allBills: 'All Bills',
    searchShops: 'Search shops...',
    settings: 'Settings',
    language: 'Language',
    fontSize: 'Font Size',
    small: 'Small',
    medium: 'Medium',
    large: 'Large',
    notPaid: 'Not Paid',
    paid: 'Paid',
    canceled: 'Canceled',
    loginTitle: 'Welcome to BMA',
    loginSubtitle: 'Manage your shop bills easily',
    loginWithGoogle: 'Login with Google',
    accessDenied: 'Access denied. Please contact admin.',
    loading: 'Processing...',
    logout: 'Logout',
    currency: '₹',
    today: 'Today',
    pending: 'Pending',
    received: 'Received',
    total: 'Total',
    count: 'Count',
    viewDetails: 'View Details',
    errorInvalidAmount: 'Please enter a valid amount',
    errorGeneral: 'Something went wrong. Please try again.',
    sortBy: 'Sort By',
    dateNewest: 'Newest First',
    dateOldest: 'Oldest First',
    amtHigh: 'High to Low',
    amtLow: 'Low to High',
    all: 'All',
    priceRange: 'Price Range',
    dateRange: 'Date Range',
    under1k: 'Under ₹1k',
    under5k: '₹1k - ₹5k',
    above5k: 'Above ₹5k',
    last7days: 'Last 7 Days',
    last30days: 'Last 30 Days',
    filters: 'Filter & Sort',
    apply: 'Apply Filters',
    clearAll: 'Clear All',
    billStatus: 'Bill Status',
    customDate: 'Custom Date',
    from: 'From',
    to: 'To',
    morning: 'Morning',
    afternoon: 'Afternoon',
    evening: 'Evening',
    night: 'Night',
    modified: 'Modified'
  },
  ta: {
    appName: 'பி.எம்.ஏ – பில் மேலாளர்',
    dashboard: 'டாஷ்போர்டு',
    shops: 'கடைகள்',
    pendingBills: 'நிலுவை பில்கள்',
    amountToCollect: 'வசூலிக்க வேண்டியவை',
    totalShops: 'மொத்த கடைகள்',
    addShop: 'புதிய கடையைச் சேர்',
    addBill: 'புதிய பில்லைச் சேர்',
    editShop: 'கடையைத் திருத்து',
    deleteShop: 'கடையை நீக்கு',
    shopName: 'கடையின் பெயர்',
    amount: 'தொகை',
    status: 'நிலை',
    save: 'சேமி',
    cancel: 'ரத்து செய்',
    confirmDelete: 'நிச்சயமாக நீக்க வேண்டுமா?',
    noShops: 'இன்னும் கடைகள் சேர்க்கப்படவில்லை',
    noPendingBills: 'பில்கள் ஏதுமில்லை 🎉',
    allBills: 'அனைத்து பில்கள்',
    searchShops: 'கடைகளைத் தேடு...',
    settings: 'அமைப்புகள்',
    language: 'மொழி',
    fontSize: 'எழுத்து அளவு',
    small: 'சிறிய',
    medium: 'நடுத்தர',
    large: 'பெரிய',
    notPaid: 'நிலுவை',
    paid: 'முடிந்தது',
    canceled: 'ரத்து',
    loginTitle: 'பி.எம்.ஏ-விற்கு வரவேற்கிறோம்',
    loginSubtitle: 'உங்கள் கடை பில்களை எளிதாக நிர்வகிக்கவும்',
    loginWithGoogle: 'கூகுள் மூலம் உள்நுழைக',
    accessDenied: 'அனுமதி மறுக்கப்பட்டது. நிர்வாகியைத் தொடர்பு கொள்ளவும்.',
    loading: 'செயல்படுகிறது...',
    logout: 'வெளியேறு',
    currency: '₹',
    today: 'இன்று',
    pending: 'நிலுவையில்',
    received: 'பெறப்பட்டது',
    total: 'மொத்தம்',
    count: 'எண்ணிக்கை',
    viewDetails: 'விவரம் பார்',
    errorInvalidAmount: 'சரியான தொகையை உள்ளிடவும்',
    errorGeneral: 'ஏதோ தவறு நடந்துவிட்டது. மீண்டும் முயற்சிக்கவும்.',
    sortBy: 'வரிசைப்படுத்து',
    dateNewest: 'புதியது முதலில்',
    dateOldest: 'பழையது முதலில்',
    amtHigh: 'அதிகம் - குறைவு',
    amtLow: 'குறைவு - அதிகம்',
    all: 'அனைத்தும்',
    priceRange: 'விலை வரம்பு',
    dateRange: 'தேதி வரம்பு',
    under1k: '₹1000 கீழ்',
    under5k: '₹1k - ₹5k',
    above5k: '₹5k மேல்',
    last7days: 'கடந்த 7 நாட்கள்',
    last30days: 'கடந்த 30 நாட்கள்',
    filters: 'வடிகட்டி & வரிசை',
    apply: 'வடிகட்டு',
    clearAll: 'அனைத்தையும் நீக்கு',
    billStatus: 'பில் நிலை',
    customDate: 'குறிப்பிட்ட தேதி',
    from: 'முதல்',
    to: 'வரை',
    morning: 'காலை',
    afternoon: 'மதியம்',
    evening: 'மாலை',
    night: 'இரவு',
    modified: 'மாற்றப்பட்டது'
  }
};

export const ICONS = {
  Dashboard: <LayoutDashboard size={20} strokeWidth={2.5} />,
  Store: <Store size={20} strokeWidth={2.5} />,
  Receipt: <Receipt size={20} strokeWidth={2.5} />,
  Settings: <Settings size={20} strokeWidth={2.5} />,
  Plus: <Plus size={24} strokeWidth={3} />,
  Back: <ArrowLeft size={24} strokeWidth={2.5} />,
  Paid: <CheckCircle2 size={18} strokeWidth={2.5} />,
  Pending: <Clock size={18} strokeWidth={2.5} />,
  Canceled: <XCircle size={18} strokeWidth={2.5} />,
  Trash: <Trash2 size={18} strokeWidth={2.5} />,
  Edit: <Edit3 size={18} strokeWidth={2.5} />,
  Search: <Search size={20} strokeWidth={2.5} />,
  Languages: <Languages size={20} strokeWidth={2.5} />,
  FontSize: <Type size={20} strokeWidth={2.5} />,
  Chevron: <ChevronRight size={18} strokeWidth={2.5} />,
  Error: <AlertCircle size={20} strokeWidth={2.5} />,
  Sort: <ArrowUpDown size={18} strokeWidth={2.5} />,
  Filter: <Filter size={18} strokeWidth={2.5} />,
  Calendar: <Calendar size={14} strokeWidth={2.5} />,
  Price: <IndianRupee size={14} strokeWidth={2.5} />,
  Close: <X size={20} strokeWidth={2.5} />
};
